// Lời khen hiện ngẫu nhiên khi đang tracking và phát hiện được khuôn mặt.
export const COMPLIMENTS: string[] = [
  "Xinh quá trời xinh! 🌸",
  "Cười lên là đốn tim đó nha!",
  "Góc nào cũng xinh hết trơn!",
  "Camera muốn tan chảy vì bạn nè ✨",
  "Auto tăng độ nét vì xinh quá!",
  "Idol đời thực là đây chứ đâu!",
  "Thần thái này ai mà không mê!",
  "Xinh xỉu ngang, giữ nguyên khung hình đi!",
  "Trời ơi dễ thương quá đi mất!",
  "Visual này xuất sắc luôn á!",
  "Gương thần phải chớp mắt vì lóa đó nha! 💫",
  "Nụ cười tỏa nắng làm cả khung hình sáng bừng!",
  "Đôi mắt biết cười, đốn tim ai đó rồi!",
  "Outfit hôm nay chuẩn concept ghê!",
  "Aura này là tự tin tỏa sáng đó nha ✨",
  "Không cần filter mà vẫn lung linh dữ vậy!",
  "Chuẩn nhân vật chính của bộ phim rồi đó!",
  "Skincare đỉnh cao, da căng bóng ghê!",
  "Đứng yên đó, gương thần ngắm thêm chút!",
  "Vibe hôm nay là “tỏa sáng rực rỡ” đây mà!",
  "Nét thanh tú này auto lên hình đẹp!",
  "Photogenic thứ thiệt là có thật luôn!",
  "Một khung hình, cả bầu trời xinh đẹp!",
  "Gò má này cười lên là có lúm đồng tiền!",
  "Đúng chuẩn “hoa hậu góc nghiêng” luôn nha!",
  "Style này lên story là auto triệu view!",
  "Mắt sáng như sao, ai nhìn cũng phải ngẩn ngơ!",
  "Trông cưng xỉu, ai mà nỡ rời mắt!",
  "Đẹp tự nhiên không cần chỉnh sửa gì thêm!",
  "Gương thần confirm: 10 điểm không có nhưng!",
  "Sắc vóc này đi đâu cũng nổi bần bật!",
  "Nhìn là muốn chụp lại ngay và luôn!",
  "Thần thái sang chảnh thấy rõ luôn á!",
  "Cả căn phòng như sáng hẳn lên vì bạn!",
  "Xinh kiểu nhẹ nhàng mà cuốn hút lạ thường!",
  "Camera 60fps cũng không bắt kịp độ lung linh!",
  "Đây chắc chắn là bức ảnh đại diện mới rồi!",
  "Duyên dáng ngút ngàn, đúng gu gương thần ghê!",
  "Làn da này chắc uống nước hoa hồng mỗi ngày!",
  "Khoảnh khắc này đáng để lưu giữ mãi mãi!",
  "Tự tin lên nào, bạn đẹp hơn bạn nghĩ đó!",
  "Nhìn cái là biết hôm nay tâm trạng cực tốt!",
  "Chân mày này chuẩn không cần chỉnh!",
  "Nghiêng đầu một cái là thành bìa tạp chí liền!",
  "Sao mà dễ thương dữ vậy trời!",
  "Phong thái này đúng chuẩn “sinh ra để tỏa sáng”!",
  "Gương thần ghen tị với độ xinh này đó nha!",
  "Một nụ cười bằng vạn lời quảng cáo!",
  "Cứ đứng đó, để gương thần lưu khoảnh khắc này!",
  "Trời sinh ra để làm nhân vật chính rồi!",
  "Vẻ ngoài này là bản giới hạn, độc nhất vô nhị!",
];
