import type { CSSProperties } from "react";

export const S: Record<string, CSSProperties> = {
  page: {
    minHeight: "100vh",
    background: "linear-gradient(180deg, #FFFEFC 0%, #FFFAF3 55%, #FFF6EC 100%)",
    fontFamily: "'Super Bouncer', 'Inter', system-ui, sans-serif",
    color: "#2B2230",
    position: "relative",
  },
  content: { padding: "24px 20px", position: "relative", overflow: "hidden" },
  wrap: { maxWidth: 1080, margin: "0 auto", position: "relative", zIndex: 1 },
  unsupportedBanner: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    background: "rgba(193,84,74,0.14)",
    border: "1px solid rgba(193,84,74,0.35)",
    color: "#7A2B24",
    borderRadius: 14,
    padding: "10px 16px",
    fontSize: 13,
    fontWeight: 600,
    marginBottom: 16,
  },
  // marginTop chừa chỗ cho mascot fixed (size 200, top:20px) ở trên — không thì đè lên tiêu đề
  hero: { textAlign: "center", marginTop: 190, marginBottom: 16, display: "flex", flexDirection: "column", alignItems: "center" },
  heroTitle: { fontSize: 20, fontWeight: 800, letterSpacing: -0.2, lineHeight: 1.3, margin: "0 0 8px", color: "#2B2230", maxWidth: 560 },
  heroSub: { fontSize: 13.5, lineHeight: 1.55, color: "#7A7180", maxWidth: 520, margin: 0 },
  heroCta: {
    display: "inline-flex",
    alignItems: "center",
    gap: 7,
    border: "none",
    background: "linear-gradient(120deg, #FF6B9B, #FF3D77)",
    color: "#fff",
    borderRadius: 999,
    padding: "9px 18px",
    fontSize: 13,
    fontWeight: 750,
    cursor: "pointer",
    boxShadow: "0 6px 16px rgba(255,61,119,0.32)",
    flexShrink: 0,
  },
  heroCtaActive: { background: "#2B2230", boxShadow: "0 6px 16px rgba(43,34,48,0.3)" },

  stage: {
    position: "relative",
    width: "100%",
    aspectRatio: "4/3",
    background: "linear-gradient(135deg, #FFE3EC 0%, #FFB0CB 55%, #FF7FA8 100%)",
    borderRadius: 22,
    overflow: "hidden",
    border: "1px solid #FFFFFF",
    boxShadow: "0 16px 36px rgba(255,61,119,0.2)",
  },
  video: { position: "absolute", inset: 0, width: "100%", height: "100%", objectFit: "cover", transform: "scaleX(-1)" },
  overlay: { position: "absolute", inset: 0, width: "100%", height: "100%", objectFit: "cover", transform: "scaleX(-1)" },
  stageEmpty: { position: "absolute", inset: 0, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: 12 },
  stageEmptyIcon: {
    width: 60,
    height: 60,
    borderRadius: "50%",
    background: "rgba(255,255,255,0.55)",
    display: "grid",
    placeItems: "center",
    color: "#2B2230",
    border: "1px solid rgba(255,255,255,0.8)",
  },
  stageEmptyText: { color: "#2B2230", fontSize: 15, fontWeight: 650 },
  stageControls: {
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
    marginTop: 14,
  },

  complimentBadge: {
    position: "absolute",
    left: "50%",
    bottom: 16,
    zIndex: 2,
    background: "linear-gradient(120deg, #FF6B9B, #FF3D77)",
    color: "#fff",
    padding: "8px 18px",
    borderRadius: 999,
    fontSize: 14,
    fontWeight: 750,
    boxShadow: "0 8px 20px rgba(255,61,119,0.35)",
    maxWidth: "88%",
    textAlign: "center",
    pointerEvents: "none",
  },

  memePanel: {
    background: "#FFFFFF",
    border: "1px solid #F8E3EB",
    borderRadius: 22,
    boxShadow: "0 8px 24px rgba(255,61,119,0.08)",
    minHeight: 240,
    display: "flex",
    overflow: "hidden",
  },
  memeEmpty: { margin: "auto", textAlign: "center", padding: 24, display: "flex", flexDirection: "column", gap: 6, alignItems: "center" },
  memeEmptyText: { fontSize: 14, fontWeight: 700, color: "#2B2230" },
  memeEmptyHint: { fontSize: 12, color: "#7A7180", maxWidth: 220, lineHeight: 1.5 },
  memeGrid: { display: "grid", gridTemplateColumns: "repeat(2, 1fr)", gap: 2, width: "100%" },
  memeImg: { width: "100%", height: "100%", objectFit: "cover", display: "block" },

  memeReveal: { display: "flex", flexDirection: "column", width: "100%" },
  memeRevealImg: {
    width: "100%",
    flex: 1,
    minHeight: 190,
    objectFit: "contain",
    background: "linear-gradient(135deg, #FFE9F1 0%, #FFF3E6 100%)",
    display: "block",
  },
  memeRevealLabel: {
    textAlign: "center",
    padding: "10px 14px",
    fontSize: 14,
    fontWeight: 750,
    color: "#2B2230",
    background: "#FFFFFF",
    borderTop: "1px solid #F8E3EB",
  },

  ratingCard: {
    marginTop: 24,
    background: "#FFFFFF",
    border: "1px solid #F8E3EB",
    borderRadius: 22,
    boxShadow: "0 8px 24px rgba(255,61,119,0.08)",
    padding: "22px 20px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 14,
    textAlign: "center",
  },
  ratingCardTitle: { fontSize: 15, fontWeight: 750, color: "#2B2230", margin: 0 },
  ratingCardNote: { fontSize: 13, color: "#B85C7E", fontWeight: 650, margin: 0 },

  scrollHint: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 4,
    marginTop: 22,
    color: "#B85C7E",
    fontSize: 12.5,
    fontWeight: 650,
  },
};
